# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class Ui_splashScreen(object):
    def setupUi(self, splashScreen):
        splashScreen.setObjectName("splashScreen")
        splashScreen.resize(500, 250)
        self.centralwidget = QtWidgets.QWidget(splashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"    background-color:rgb(25, 35, 45);\n"
"    color:rgb(220,220,220);\n"
"    border-radius:10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label_title = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_title.setGeometry(QtCore.QRect(20, 50, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(20, 160, 441, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color:rgb(98,114,164);\n"
"    color:rgb(200,200,200);\n"
"    border-style:none;\n"
"    border-radius:10px;\n"
"    text-align:center\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.54, stop:0 rgba(255, 101, 222, 255), stop:1 rgba(170, 85, 255, 255));\n"
"    }")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_loading.setGeometry(QtCore.QRect(10, 190, 461, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(98, 114, 164);\n"
"}")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_desc = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_desc.setGeometry(QtCore.QRect(10, 90, 461, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_desc.setFont(font)
        self.label_desc.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(98, 114, 164);\n"
"}")
        self.label_desc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_desc.setObjectName("label_desc")
        self.horizontalLayout.addWidget(self.dropShadowFrame)
        splashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(splashScreen)
        QtCore.QMetaObject.connectSlotsByName(splashScreen)

    def retranslateUi(self, splashScreen):
        _translate = QtCore.QCoreApplication.translate
        splashScreen.setWindowTitle(_translate("splashScreen", "MainWindow"))
        self.label_title.setText(_translate("splashScreen", "<html><head/><body><p><span style=\" font-weight:600;\">MARITIME </span>SURVEILLANCE </p></body></html>"))
        self.label_loading.setText(_translate("splashScreen", "Loading ..."))
        self.label_desc.setText(_translate("splashScreen", "<strong> Welcome </strong> to a safer sea"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    splashScreen = QtWidgets.QMainWindow()
    ui = Ui_splashScreen()
    ui.setupUi(splashScreen)
    splashScreen.show()
    sys.exit(app.exec_())
